[package]
name = "write_x86_64"
version = "0.1.0"
authors = [
    "Samuel VIVIEN <samuel.vivien@ens.psl.eu>"
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
